### PR TITLE
Squadron text

### LINKED ISSUE #10: Ability to build squads from a raw text file
Should have things like squad name, speed, hull, keywords

### PR DESCRIPTION
**Pull request by danbuis**
This PR is based on the game loop stuff because it depends on some of the file structure, NOT the logic contained in that pull request.

The goal of this PR is to create a text document with the wave 1 squadrons of all 4 factions.  (ie not rogues and villains, or the squadron2 of the civil war era factions)

### CODE REVIEW

**Comment by danbuis** [comment]
@Sobonis01 Double check that I put all the info in correctly and consistantly.  I wouldn't be surprised if I missed a keyword or points cost somewhere.

**Review by Sobonis01 — APPROVED** [review]

**Review by Sobonis01 — COMMENTED** [review]
How do you want to define the special abilities of each squad?  Should we put down abilities|nickname or Howelrunner ability

**Comment by danbuis** [comment]
That will be an upgrade of the same name that gets attached to the squads at creation.

**Review by Sobonis01 — APPROVED** [review]

**Comment by danbuis** [comment]
If you are content with the file, I'll go ahead and merge it, or you can.  Either way.  As long as you are satisfied let's get this one merged.

**Pull request merged**
