### PR TITLE
Squaron render v1

### LINKED ISSUE #27: Render some squadrons
Render all the squadrons to our test bed screen

- [x] Add some basic solid color rendering functions
- [x] Figure out how to put all the things together into one "container" / data structure
- [x] Test out the basic rendering
- [x] Make a Squadron for each one available and render to the DemoMap (this will test out moving a squad, might as well do some rotation too)
- [x] Correct any file names that need it
- [x] Unit tests for movement the parent Squadron object
- [x] Move items to GameConstants file or whatever it is called
~~- [ ] Refactor~~ Opened a skillion issue cards for refactoring/tech debt
- [x] Re check tests
- [x] Render squadrons and map (this is currently not working as intended at the time of writing)
- [x] Documentation on changed files

### PR DESCRIPTION
**Pull request by danbuis**
## Goal of Pull Request
Render squadrons to the screen

## Potential Tasks

  - [x] Connects to #???
  - [x] Meets the DefDone of the linked issue
  - [x] All tests pass (Although the reviewer should run them to make sure)
  - [x] Other?

## Any other pertinent information
Rendering the whole of the squad collection is not going to be a permanent part of the code base.  Its just a temporary fixture for the first section of development and will be phased out as the menu navigation etc begins to be put in place.  There are a few things I'm not super happy about here, but those have been moved into separate issues in the interest of getting this out the door faster and not bloating it.

### CODE REVIEW

**Comment by danbuis** [comment]
@Sobonis01 when you review this please let me know if anything is unclear, or if you have any questions about why I made some of my decisions, or if you see something you'd like to see tested better/differently/at all.

**Review by Sobonis01 — COMMENTED** [review]
so this file creates the map for the demo. 
it also imports the objects from the BBD library?

**Review by Sobonis01 — APPROVED** [review]
What you added was a line of code to open up a new window by adding the new Window.WindowOptions(),

**Comment by danbuis** [comment]
Yeah.  This creates a 3x3 map and such.

RE: bbd library.
It looks like I brought in a new version a few PRs ago, you can see that if you filter to closed PRs.  It looks like in the process though I didn't actually update the code that interfaces with the library.  There were some pretty substantial modifications to the core classes in order to be able to do selection via mouse.

**Pull request merged**
