### PR TITLE
Game loop v2

### LINKED ISSUE #5: Build out a basic render for a game view
At this point it isn't anything fancy.  We are looking for a black 3x3 area, with maybe some placeholder images with some text for things.  Basically building out a very rough view of what the game might look like.

### PR DESCRIPTION
**Pull request by danbuis**
Happy New Year.

Got the backbone in place for the game.  Basically its all the boring boilerplace code in place to get things going.

All it does right now is draw a 3x3 map to the screen.

It does however have a TON of code drawing from my BBDGameLibrary codebase, so feel free to ask any questions you might have before merging.

To ask about a specific chunk of code you can go over to the "files changed" tab and then click and drag the approriate line numbers to highlight.  This will open up a comment box attached to those lines and make it super easy for me to see what you are asking about.

Before merging though, I want you to verify that you can import this into intelliJ and get it to run correctly without any fuss.  IntelliJ is my current Interactive Development Environment (IDE) of choice for java.

### CODE REVIEW

**Comment by Sobonis01** [comment]
Looks good

**Review by Sobonis01 — DISMISSED** [review]
I dont think we are missing anything but under src/engine/GameConstants.java I only see the large base ships sizes?  Should we add small in or are we just testing it with large first?

**Comment by danbuis** [comment]
I see it in lines 30 to 33 of the file

**Review by Sobonis01 — COMMENTED** [review]
So this file is just to warm up the BBD Game library engine?  Then onto the components and final into the game itself?

**Review by Sobonis01 — COMMENTED** [review]
This file will be to hold the game itself, like the AI?  Can we use the Vassal interface for the non AI side?  Kike the Set button to let the computer know when your done?

**Comment by danbuis** [comment]
Don't forget you can comment directly on the code.  You can go to the Files changed tab up there and highlight the code to attach comments directly to the lines in question.  That will also give me the ability to comment directly o that thread.

`So this file is just to warm up the BBD Game library engine?`  Assuming you are talking about the ArmadaAIMain class, yes.  The BBDGamesLibrary.Engine class is the entry point into things to handle rendering, handling input, setting up update loops and tieing them all together.  We can make classes that fit into its expectations and it will handle a lot of things behind the scenes.

`This file will be to hold the game itself, like the AI?`  Assuming you are talking about ArmadaGame, then yes, with an asterisk.  That class will likely be the bucket that holds everything and has a way to access all objects on both sides.  The asterisk is because we are so early in the process that everything is subject to change.

`Can we use the Vassal interface for the non AI side?`  We can do anything we want.  We aren't constrained by vassal at all.  I figure we'll need some sort of submit/final answer/set/whatever thing.  The "Set" in vassal has its roots in circa 2014 in x-wing vassal.  Don't feel tied to anything at all in vassal.

**Comment by danbuis** [comment]
@Sobonis01 also please make sure that when you open this branch in your IDE you can get it to run correctly.  This will prove to me that I set things up right and got the right dependancies etc in there.

I'd super like for this one to be merged in the next 7ish days so that I can get things upgraded to the next version of BBDGamesLibrary before we start getting more things that depend on what will soon be outdated code.

**Review by Sobonis01 — COMMENTED** [review]
I need to add the @Param to the ship file.  To tell people what each thing is. 
     * @param type What type/hull is the Squadron, ie X-wing
     * @param name The name of the Squadron, ie Biggs Darklighter, or X-wing
     * @param unique Is this squadron unique
     * @param fullHealth How much health does it start with
     * @param maxSpeed How much distance can it move at full speed
     * @param antiShipDice anti ship armament
     * @param antiSquadronDice anti squadron armament
     * @param keywords keywords the Squadron has access to. Must have a value, even if it is an empty list
     * @param pointsValue How many points is it worth
     * @param defenseTokens What defense tokens, if any, does it have?  Must have a value, even if it is an empty list

is the parsers the item that test squadronfactory out?
Also on the squadrons themselves you have it written as DefenseToken, but in the constructor it is defenseTokens will that cause a problem?

**Review by Sobonis01 — APPROVED** [review]
We can approve it understand what I need to fix on my ship list file.

**Comment by danbuis** [comment]
@Sobonis01 regarding the DefenseTokens on the squad text file...

No.  Line 82 is grabbing the correct key and then setting a variable equal to the value.

We don't need to have a perfect match between text file and constructor because Java doesn't really work that way.  We have to tell it where things need to go.  Line 84 sets the class variable for the SquadronFactory, which is then passed into the constructor later.

Java doesn't have "keyword" constructors, it has positional constructors.  Ie we don't type new Squadron(hull=4, speed=5)  Java assumes as long as the types are the right quantity and order than this must be the function we want to use.

**Pull request merged**
