### PR TITLE
Squadron Objects

### LINKED ISSUE #11: Squadron objects
There will be a few steps to this issue.

We are starting with the text file and have to get to rendering squads on the screen

Tasks to complete include
 - [x] Define a squadron object
 - [x] Parse a the text file to build a dictionary of squadron objects
 - [x] Incorporate some error handling on parsing to catch things like missing fields, badly typed inputs, illegal values etc.
 - [x] Tests to ensure that both object parsing/creation works, and to verify that error handling works
 - [x] Pull error handling out so that ship parsing can take advantage of the same sort of error checking and ultimately do adhere to DRY

### PR DESCRIPTION
**Pull request by danbuis**
Goal of this PR is to get some basic squadrons loaded into the game.

Provide some basic tooling to handle bad inputs.

### CODE REVIEW

**Comment by danbuis** [comment]
This one started out being building squadron objects and rendering them.

Error handling and testing ended up being substantial enough that I decided to cut this one here and leave it where it is.

**Comment by danbuis** [comment]
I think the last tasks for this one are
- Clean up error throwing
~~- Move faction validations to utils~~
~~- Ensure that we aren't partway through building a squad when we get to the end.~~

**Comment by danbuis** [comment]
I don't have a good way of handling error throwing here in these classes.

The tests rely on the exceptions being thrown.  Doing a try/catch just handles the exception without throwing it, so the tests crash.

I think right now the best plan is to kick exception handling down the road to whatever ends up using this class.

**Review by Sobonis01 — APPROVED** [review]

**Review by Sobonis01 — COMMENTED** [review]
So is Private Void there to test to make sure everything runs right? But it should not return any value?

**Review by Sobonis01 — APPROVED** [review]

**Review by Sobonis01 — APPROVED** [review]
I think I understand this.

**Review by Sobonis01 — COMMENTED** [review]
So it would work like this,  computer would pull the item, which would be public class squads, then it would search for the actual specific information for that squad aka the stats, which are under private to keep them from messing with each other, then it builds the squads with Boolean to see if the values equal say a tie fighter? Or am I wrong?

**Review by Sobonis01 — COMMENTED** [review]
so will this be the actual code that creates the squads?

**Review by Sobonis01 — APPROVED** [review]
I understand why you needed the ships as text as you needed something to pull from!

**Review by Sobonis01 — COMMENTED** [review]
Could use numbers to help the computer know which fighter squad it is moving.  Like Arc 170 1 or Arc 170 2?

**Review by Sobonis01 — COMMENTED** [review]
never mind you already answered the question.

**Comment by danbuis** [comment]
@Sobonis01 "Could use numbers to help the computer know which fighter squad it is moving. Like Arc 170 1 or Arc 170 2?"

So our Squadrons object that has the hashmap serves as a master copy of all squadrons that were parsed.

When a new Squadron object is created it is copied from that hashmap master set and at that point it is attached to both a variable, like "squad1" or mySquadArrayList.add(new Squadron("ARC-170") AND it gets an address in memory.  If we were to say does "squad1" equal "squad2" it actually checks the memory addresses unless we tell it to use something else (by defining Squadron.equals(other))

The variable name is up to whatever is using the squadron objects.  Memory address is out of our control

**Comment by danbuis** [comment]
@Sobonis01 `So it would work like this, computer would pull the item, which would be public class squads, then it would search for the actual specific information for that squad aka the stats, which are under private to keep them from messing with each other, then it builds the squads with Boolean to see if the values equal say a tie fighter? Or am I wrong?`

Close.

Whatever wants to create a squad first needs to have a Squadrons object, which now that I think about definitely needs a better name.

We would do something like 

`import engine.parsers.Squadrons
Squadrons squadronMasterCopy = new Squadrons()`

The constructor for that class actually builds one instance of every squad, see line 76 and 84.  That single instance is put into a map for retrieval later.  Now every time we want to make a new Squadron we don't need to open and parse the text file until we find what we need.  This might be a bit of premature optimization, but it was easy to implement.  (Thinking of someone like our local friend who absolutely WILL recreate something with 100+squads on a side)

I think we touched on the reason for private vs public, but I'll reiterate again here.  The goal is to make sure that each Object, so a Squadron object, can't access or modify the variables in another Object (Squadron, Ship, Card etc)  We want every object to jealously guard its data, and give it public methods for other objects to interact with it.  So a Squadron will probably have a public void takeDamage(int dmg) function.  That function doesn't care where the damage comes from, because that doesn't matter, but it lets it decide what to do with that damage (brace, scatter, etc)

`then it builds the squads with Boolean to see if the values equal say a tie fighter? Or am I wrong?`
wrong.  the only time booleans are used is the unique field, where I used the Boolean wrapper for the primitive boolean so that it could be null.

To build a tie fighter with our earlier object we would do 
`Squadron tie_fighter1 = squadronMasterCopy.getSquadron("TIE-Fighter")`
We can verify what kind of squadron it is by doing something like
`tie_fighter1.getType()`

**Comment by danbuis** [comment]
@Sobonis01 I renamed the `Squadrons` parser class to `SquadronsFactory` as that is a better indication of its purpose, ie building Squadron objects.  I also added some documentation around the new classes and functions.  

I'm happier with this one now

**Review by Sobonis01 — APPROVED** [review]

**Review by Sobonis01 — COMMENTED** [review]
Need to correct DefenseTokens to defenseToekens to match other files

**Pull request merged**
