### PR TITLE
Raw text

### PR DESCRIPTION
**Pull request by Sobonis01**
[Ships as Raw.txt](https://github.com/danbuis/ArmadaAIEngineNew/files/5826003/Ships.as.Raw.txt)

### CODE REVIEW

**Comment by Sobonis01** [comment]
having issues doing a pull request atm. :(

**Comment by danbuis** [comment]
Is this different than #30

Gut feel is no since its the same branch

**Comment by danbuis** [comment]
@Sobonis01 yeah.  You'll want to make sure each line has key|value

Those NavChart| Lines will be problematic.  I suggest removing them and just having Speed1|XXX etc

**Comment by danbuis** [comment]
Closed as a duplicate of #30

**Pull request closed without merging**
