### PR TITLE
Image assets

### LINKED ISSUE #22: Bring over some vassal graphics
For now what i'm worried about are the ship models (not the bases), squadron models (not the bases) and the maps.

### PR DESCRIPTION
**Pull request by danbuis**
Add maps, ship, and squad graphics.

These will be used to render game components.

### CODE REVIEW

**Review by Sobonis01 — DISMISSED** [review]
So we are pulling assist from vassal, each ship has a fade no fade. Also the shield dials hull etc are blank as those can be changed right?  
In the ship builder we will have to make a line that says, HEY go pull 
assets/images/ships/ship_ISD noFade.png for isd at some point.

**Comment by danbuis** [comment]
Honestly I'm planning on nixing everything on those images that isn't the ship model.  For the core boxes I've already erased the bases.

We will be rendering our own bases because that gives us much more control, and guarantees that what shows up on the screen will match up with the numbers in the ship_text file.

**Comment by danbuis** [comment]
Also the base branch was change is intentional.

When I made this pull request it was relying on stuff in the game_loop branch, so it was my starting point, or my base.

Changing the base back to develop does a few things that are problematic...
1) It makes the commits in the game_loop branch show up here because they are in the history for this branch, but not in develop.  This makes it less clear what is new here vs what is old.
2) Heaven forbid this one is reviewed and merged first, we might accidentally bypass a proper review on the game_loop branch.

The takeaway is that everything will find its way to develop, but it doesn't need to go directly there.  Sometimes it is okay to take an indirect route.

Github should automatically change the base branch once game_loop is merged though, so it automatically assists us in getting things to the proper place.

**Comment by danbuis** [comment]
@Sobonis01 Oh, I see the base change was automatic.  My bad.  Sorry about that.

**Comment by danbuis** [comment]
@Sobonis01 Any chance you remember what was preventing this one from being merged?  Its not terribly urgent, but it is an old one and I'm doing a bit of housecleaning.

**Comment by danbuis** [comment]
Too slow, I'm merging this one, especially since it doesn't have any logic in the additions, just new assets

**Pull request merged**
